### PR TITLE
fix test project setup ...

### PR DESCRIPTION
**Pull request by ANierbeck**
Hi, 

did a quick cleanup, as the war test only tests the war part. 
It's sufficient to start with a war containing the karaf/Pax-Web Container. 
Therefore this should be sufficient to get you further going. 
The test fails as no application seems to be deployed with the karaf container embedded in the sample. 
Most likely it could be interesting to add this via some external tooling. 

regards, Achim

### CODE REVIEW

**Comment by sergehuber** [comment]
Hello Achim, 

Thank you so much for taking a look at this. I finally managed to get it working today, it seems like our work got send out at the same time to Github. I have the BundleContext working now and I can therefore now start deploying bundles and implementing tests.

I see in your contribution that you have removed a lot of the "framework code" that I copied over from the Tomcat tests. Do you think it is better to start from scratch or should we continue using it ? 

I'm not sure how much I can do over the week-end but I'll try to have at least a test fully working on Monday (after that I have to focus on other things but I hope I can still keep this moving) ?

Once again thank you so much for helping with this,
cheers,
  Serge...

**Comment by ANierbeck** [comment]
Hi Serge, 

I just removed the un-needed OSGi stuff from the web-only test. Cause if you want to test the war-embedded-karaf you actually can't connect to the karaf internal stuff anymore. It's going to be a pure external itest. 

regards, Achim

**Comment by sergehuber** [comment]
Hello Achim,

I'm not sure I understand what you mean by the war-embedded-karaf unless that's another name for my sample War ? 

What I was aiming for in the integration test was to start up the war probe with the embedded Karaf and retrieves the frameworks BundleContext to deploy the needed war/bundle for each test of my pax-web-web app-bridge.

It took me a while to get this setup but I believe I finally got the retrieval of the Embedded BundleContext working so I could now just deploy what's needed for each integration test. 

Normally I should then be able to use the same tests as for the other containers no ?

Does this sound ok or maybe I should do this differently ?

**Comment by ANierbeck** [comment]
Hi Serge, 

sorry for "renaming" :)
Ok, maybe I should elaborate a bit more about why I changed the setup. 
We have to differentiate between running pax-exam OSGi integration tests and pax-exam war tests, both are completely different. 
The first one is only for OSGi "framework" related tests and only works for tests where the test-framework is started by the JUnit testclass. For web-related Pax-Exam tests you only start a web container where your local project is deployed. That's the part I changed. I made sure your test is a web-only test where the web-test starts the sample war (containing the karaf runtime). 
It seemed to work for me cause I didn't get a 404, but the sample webapplication hasn't been started within karaf. Actually I'm not sure that your expectation of mixing both use-cases is really working. 

regards, Achim

**Comment by sergehuber** [comment]
Ok I've incorporated manually a lot of the changes here. I finally understood the problem with the listeners, I was exposing pax-web-spi at different levels in the class loader hierarchy so this was causing problems. 

I did however keep the OSGi core dependency because I have use the BundleContext to deploy the WAR inside the Karaf container for testing the PAX Web Webapp Bridge implementation. It seems to work for the simple war-simple sample application.

So now I have this first integration test fully working, I must now concentrate on putting more in place. I tried integrating the change on the configuration but unfortunately that didn't seem to work. If you want to give it a try that would be great but I suggest that we do this in a separate pull request as I have something working right now.

I'll close this pull request now, I hope that's ok.

**Comment by ANierbeck** [comment]
fine with me :)

**Comment by ANierbeck** [comment]
to make it easier, how about having this special branch in the ops4j repo?
You should already have write access.

**Comment by sergehuber** [comment]
I was thinking about moving this to the main repository once I have a bit more implemented, but if you prefer we do it early that's fine with me. I was planning on doing a pull request at some point.

**Comment by ANierbeck** [comment]
hi,

yeah just as special branch is fine with me :-)

regards, Achim

2016-01-25 10:49 GMT+01:00 Serge Huber <notifications@github.com>:

> I was thinking about moving this to the main repository once I have a bit
> more implemented, but if you prefer we do it early that's fine with me. I
> was planning on doing a pull request at some point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-174453401>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by sergehuber** [comment]
Ok how should we proceed, should I initial a pull request already or do you want to wait ?

cheers,
  Serge…

**Comment by ANierbeck** [comment]
Start with an extra pull request for a new branch,
after that you can start pulling it over to the pax-web project (in the
extra branch)
It's the same procedure we did for the JSF-Resource branch and
optimizations.
Right now that branch is still work in progress, but every now and then
some of those are merged back into master.
So I'm fine with that approach.

regards, Achim


2016-01-25 11:05 GMT+01:00 Serge Huber <notifications@github.com>:

> Ok how should we proceed, should I initial a pull request already or do
> you want to wait ?
>
> cheers,
> Serge…
>
>
> > On 25 janv. 2016, at 11:00, Achim Nierbeck <notifications@github.com>
> wrote:
> >
> > hi,
> >
> > yeah just as special branch is fine with me :-)
> >
> > regards, Achim
> >
> > 2016-01-25 10:49 GMT+01:00 Serge Huber <notifications@github.com>:
> >
> > > I was thinking about moving this to the main repository once I have a
> bit
> > > more implemented, but if you prefer we do it early that's fine with
> me. I
> > > was planning on doing a pull request at some point.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-174453401
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> > Apache Member
> > Apache Karaf <http://karaf.apache.org/> Committer & PMC
> > OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer
> &
> > Project Lead
> > blog <http://notizblog.nierbeck.de/>
> > Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>
> >
> > Software Architect / Project Manager / Scrum Master
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-174456963
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-174458237>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by sergehuber** [comment]
It's not clear to me how do I create the extra pull request for a new branch ? I'm ready to send my pull request to the ops4j project but I don't know how to perform this first step. 

I was thinking about calling the new branch PAXWEB-606-Servlet-Bridge link in my repo.

**Comment by ANierbeck** [comment]
Hi, 

yes you need to create a branch and do a pull request on the branch. 
This one was similar: 
https://github.com/ops4j/org.ops4j.pax.web/pull/33

regards, Achim

**Comment by sergehuber** [comment]
Ok I created the PAXWEB-606 Servlet Bridge branch and generate a pull request towards it. I hope I did everything right.

cheers,
  Serge…

**Comment by ANierbeck** [comment]
seems to be ok, clear to go ahead ... it's git so if we screw master we
still can do a rollback :)



2016-01-28 8:57 GMT+01:00 Serge Huber <notifications@github.com>:

> Ok I created the PAXWEB-606 Servlet Bridge branch and generate a pull
> request towards it. I hope I did everything right.
>
> cheers,
> Serge…
>
>
> > On 28 janv. 2016, at 08:29, Achim Nierbeck <notifications@github.com>
> wrote:
> >
> > Hi,
> >
> > yes you need to create a branch and do a pull request on the branch.
> > This one was similar:
> > ops4j#33 <https://github.com/ops4j/org.ops4j.pax.web/pull/33>
> > regards, Achim
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176030849
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176042793>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Comment by sergehuber** [comment]
Are you saying I should accept the pull request myself ? I’m fine doing it I just want to make sure I understand you correctly :) 

cheers,
  Serge…

**Comment by ANierbeck** [comment]
yep :-)

2016-01-28 10:04 GMT+01:00 Serge Huber <notifications@github.com>:

> Are you saying I should accept the pull request myself ? I’m fine doing it
> I just want to make sure I understand you correctly :)
>
> cheers,
> Serge…
>
> > On 28 janv. 2016, at 09:58, Achim Nierbeck <notifications@github.com>
> wrote:
> >
> > seems to be ok, clear to go ahead ... it's git so if we screw master we
> > still can do a rollback :)
> >
> >
> >
> > 2016-01-28 8:57 GMT+01:00 Serge Huber <notifications@github.com>:
> >
> > > Ok I created the PAXWEB-606 Servlet Bridge branch and generate a pull
> > > request towards it. I hope I did everything right.
> > >
> > > cheers,
> > > Serge…
> > >
> > >
> > > > On 28 janv. 2016, at 08:29, Achim Nierbeck <notifications@github.com
> >
> > > wrote:
> > > >
> > > > Hi,
> > > >
> > > > yes you need to create a branch and do a pull request on the branch.
> > > > This one was similar:
> > > > ops4j#33 <https://github.com/ops4j/org.ops4j.pax.web/pull/33>
> > > > regards, Achim
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176030849
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176042793
> >
> > > .
> > >
> >
> >
> >
> > --
> >
> > Apache Member
> > Apache Karaf <http://karaf.apache.org/> Committer & PMC
> > OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer
> &
> > Project Lead
> > blog <http://notizblog.nierbeck.de/>
> > Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>
> >
> > Software Architect / Project Manager / Scrum Master
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176069586
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergehuber/org.ops4j.pax.web/pull/1#issuecomment-176072889>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Pull request closed without merging**
